### ISSUE TITLE
Guide doesn't end on blocks where start indent and end indent levels are different

### ISSUE THREAD

**Issue by angrybakon** [zk-phi/indent-guide#21]
Title pretty much says it all.

Some examples:

### Elisp

    (dolist (k '([mouse-1] [down-mouse-1] [drag-mouse-1] [double-mouse-1] [triple-mouse-1]
    |            [mouse-2] [down-mouse-2] [drag-mouse-2] [double-mouse-2] [triple-mouse-2]
    |            [mouse-3] [down-mouse-3] [drag-mouse-3] [double-mouse-3] [triple-mouse-3]))
    | (global-unset-key k))
    |
    |

### Python

    def eat(self):
    |   """Eat chicken wings
    |   """
    |
    |   for wing in bucket:
    |   |   self.feed()
    |   |   print 'Mmh... yummy !'
    |   |
    |   |

The guides stop when they reach the beginning of the next block.

Thanks : ]

**Comment by zk-phi** [comment]
implemented.
