### ISSUE TITLE
Blocking in `list-packages`

### ISSUE THREAD

**Issue by dinse** [zk-phi/indent-guide#28]
Is anyone else experiencing blocking due to `indent-guide` in the packages list using Emacs 25.0.50?

**Comment by kyanny** [comment]
Same happens at Emacs 24.4.1 on Mac OSX Yosemite. `GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-11-07 on Kensukes-MacBook-Pro.local`

Issue and how to reproduce:

I enabled `indent-guide-global-mode`.
When I open package list menu by `M-x package-list-packages` and call `M-x end-of-buffer`, CPU utilization almost 100% and Emacs hang.

I'm totally not sure why this happen, and I couldn't debug by `edebug`.

Only 1 solution I figured out is disable indent-guide-mode at package-menu-mode.
So finally my setting is below.

```elisp
(require 'indent-guide)
;; add package-menu-mode to ignore list of indent-guide-mode
;; this must be evaluated before calling indent-guide-global-mode
(setq indent-guide-inhibit-modes '(dired-mode package-menu-mode))
(indent-guide-global-mode)
```

**Comment by zk-phi** [comment]
indent-guide implementation is not very efficient and it gets notably slow when highlighting huge blocks.
we probably should tweak the algorithm later, but anyway disabling `indent-guide-mode` in `package-menu-mode` seems a reasonable solution for now.
