### ISSUE TITLE
Don't indent the first level?

### ISSUE THREAD

**Issue by chenglou** [zk-phi/indent-guide#30]
First level is stuck to the line number bar/border and there's no need to highlight the indent there (ever?). I think this would be a better default?

**Comment by zk-phi** [comment]
do you mean something like this ?

```
(defun indent-guide--active-overlays ()
  "Return the list of all overlays created by indent-guide."
  (delq nil
  |     (mapcar
  |     |(lambda (ov)
  |     || (and (eq (overlay-get ov 'category) 'indent-guide) ov))
  |     |(overlays-in (point-min) (point-max)))))
```

**Comment by chenglou** [comment]
Yes

**Comment by zk-phi** [comment]
it's quite easy to implement, but I wonder if it's really useful and should be default.
is this issue related to #21 ?

**Comment by chenglou** [comment]
Not really related I believe.
Just a suggestion though. I find it worthwhile, but maybe as a default it's too much.

**Comment by zk-phi** [comment]
thanks for quick reply.
okay i'll implement as an option firstly, and try it. thanks.

**Comment by zk-phi** [comment]
thanks for quick reply.
okay i'll implement as an option firstly, and try it. thanks.

**Comment by zk-phi** [comment]
updated.
try `(setq indent-guide-threshold 0)` to avoid zero-column guide line.

**Comment by chenglou** [comment]
:+1:
