### ISSUE TITLE
How to always display all indent guide in a buffer?

### ISSUE THREAD

**Issue by cheunghy** [zk-phi/indent-guide#36]
It is extremely useful in indentation based html template languages.

**Comment by zk-phi** [comment]
Impossible for now. The lines are drawn only in the current block to avoid performance issues.

**Comment by cheunghy** [comment]
How about drawn it on visible region?

**Comment by zk-phi** [comment]
indent-guide.el recognizes the structure of the current block by searching smaller indentation (than the current line) backward, and to implement the feature probablly we need to change the algorithm.
