### ISSUE TITLE
tag release?

### ISSUE THREAD

**Issue by dunn** [zk-phi/indent-guide#38]
It'd be great to have this available on MELPA stable!

Thanks <3

**Comment by dunn** [comment]
Thank you!

I notice, though, that the version defined in `indent-guide.el` is 2.3.0 while the tagged version is 20160630.  Is there a reason for that difference?

**Comment by zk-phi** [comment]
There's no reason, so I'll change it if it seems problematic (I'm sorry but I personally don't use melpa-stable, and I'm not so familiar with it).

**Comment by dunn** [comment]
MELPA stable extracts its version information from the tags, so it's conventional to use the version of the software as the tag; but it's not a huge deal if you're going to be tagging versions based on the date.
