### ISSUE TITLE
not show full indent guide when non continious indent

### ISSUE THREAD

**Issue by futurist** [zk-phi/indent-guide#41]
see below code

````
<div>
    <p>text text</p>
<p>text text</p>
    |<p>text text</p>
</div>
````

When 2nd p tag no indent, the indent-guide won't work as expected.

The expected result is: show guide on 1st p and 3rd p, but now the result is only on 3rd p

**Comment by zk-phi** [comment]
that's the normal behavior. indent-guide does not understand the DOM structure but just understands the indentation.

**Comment by zk-phi** [comment]
closing
