### ISSUE TITLE
work with git

### ISSUE THREAD

**Issue by seventhking** [zk-phi/indent-guide#46]
It seems that a git project file modified a lot, then move cursor might block some time in indent-guide-mode.

**Comment by zk-phi** [comment]
indent-guide just recognizes the indentation by scanning the current buffer and does not use git internally, so I hope it does not change the behavior even if the file is under a git project.
If you are using Emacs >= 24.0, a built-in profiler is available to detect which function actually is consuming the CPU time, which will be helpful to inspect this issue further.
